version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: revenda-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: revendasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    restart: unless-stopped
    networks:
      - revenda-network
      
  zipkin:
    image: openzipkin/zipkin
    container_name: revenda-zipkin
    ports:
      - "9411:9411"
    networks:
      - revenda-network
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: revenda-rabbitmq
    ports:
      - "5672:5672"   # Porta padrão AMQP
      - "15672:15672" # Porta da interface administrativa
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - revenda-network

volumes:
  postgres-data:
    name: revenda-postgres-data
  rabbitmq-data:
    name: revenda-rabbitmq-data

networks:
  revenda-network:
    name: revenda-network
    driver: bridge 